/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import model.Diary;

/**
 *
 * @author lenovo
 */
public class DiaryFrameDetail extends javax.swing.JFrame {

    int positionX = 0;
    int positionY = 0;
    
    //deklarasi variabel untuk untuk status lihat
    int status = 0;
    private final int lihat = 0;
    
    public DiaryFrameDetail() {
        initComponents();
        status = 1;
    }
    
    //konstruktor utama yang digunakan untuk melihat detil data yang dipilih
     public DiaryFrameDetail(Diary diary) {
        initComponents();
        
        
        status = lihat;
        taCatatan.setLineWrap(true);
        setLocationRelativeTo(this);
        getContentPane().setBackground(new java.awt.Color(19, 19, 19));
        
        //menampilkan data baru yang sudah diambil sebelumnya pada design detil
        lbJudul.setText(diary.getJudul());
        lbTanggal.setText(diary.getTanggal());
        taCatatan.setText(diary.getCatatan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taCatatan = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbTanggal = new javax.swing.JLabel();
        lbJudul = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        btnEkspor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        taCatatan.setEditable(false);
        taCatatan.setBackground(new java.awt.Color(51, 51, 51));
        taCatatan.setColumns(20);
        taCatatan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        taCatatan.setForeground(new java.awt.Color(255, 255, 255));
        taCatatan.setLineWrap(true);
        taCatatan.setRows(5);
        taCatatan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(taCatatan);

        jLabel6.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Catatan");

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));

        lbTanggal.setFont(new java.awt.Font("Cooper Black", 0, 20)); // NOI18N
        lbTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbTanggal.setText("Tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTanggal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lbTanggal)
                .addGap(15, 15, 15))
        );

        lbJudul.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        lbJudul.setForeground(new java.awt.Color(255, 255, 255));
        lbJudul.setText("Judul");

        btnTutup.setBackground(new java.awt.Color(27, 188, 155));
        btnTutup.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        btnTutup.setForeground(new java.awt.Color(51, 51, 51));
        btnTutup.setText("Tutup");
        btnTutup.setAutoscrolls(true);
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnEkspor.setBackground(new java.awt.Color(255, 153, 0));
        btnEkspor.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        btnEkspor.setForeground(new java.awt.Color(255, 255, 255));
        btnEkspor.setText("Ekspor");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbJudul)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(563, 563, 563))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnEkspor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTutup)
                    .addComponent(btnEkspor))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporActionPerformed
        try{
            //buat file baru
            BufferedWriter out = new BufferedWriter(new FileWriter("./exportfile/catatan/Catatan "+ lbJudul.getText() +".txt"));
            
            //mengambil data pada label dan text area 
            out.write("Tanggal : "+ lbTanggal.getText()+"\n");
            out.write("Judul  : "+ lbJudul.getText()+"\n");
            out.write(taCatatan.getText());
                       
            //close editor
            out.close();
            // tampilkan dialog bisa berhasil
            JOptionPane.showMessageDialog(null, "Catatan berhasil disimpan dalam file");
            //tutup output stream
        } catch(Exception e){
            //dialog jika ada error
            System.err.println("Error : "+ e.getMessage());
        }
    }//GEN-LAST:event_btnEksporActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //set posisi kordinat x dan y dari mouse yang digerakkan 
       //merupakan bagian dari panel undecorated agar bisa di drag
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        //set posisi kordinat x dan y menjadi 0
       //merupakan bagian dari panel undecorated agar bisa di drag
        positionX = evt.getX();
        positionY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaryFrameDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaryFrameDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaryFrameDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaryFrameDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaryFrameDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JTextArea taCatatan;
    // End of variables declaration//GEN-END:variables
}
